### ISSUE TITLE
German quote improvement

### ISSUE THREAD

**Issue by d-klotz** [LeuAlmeida/leunardo-dot-dev#3]
https://github.com/LeuAlmeida/leunardo.dev/blob/e99c7ba40aaf6a4ec70c8d9ccfae90bf9a6f5eb4/src/components/landing/Blockquote/index.js#L38

"Sie werden vielleicht nie wissen, welche Ergebnisse von Ihren Handlungen kommen, aber wenn Sie nichts tun, wird es keine Ergebnisse geben."

**Comment by LeuAlmeida** [comment]
Thank you @d-klotz ! I improved that [here](https://github.com/LeuAlmeida/leunardo.dev/commit/90ddd15fa6c5a6b9b826ca662d445f4f218c7ffe).
